language: cpp
compiler:
    - clang
    - gcc
before_install:
    - git clone git://github.com/cpputest/cpputest.git
    - cd cpputest/
    - ./configure
    - make
    - export CPPUTEST_HOME=$PWD/cpputest
    - cd ..
script:
    - cmake . && make && make test
